baseURL = "https://suojelualueet-pirkanmaa.pages.dev/"
languageCode = "fi"
title = "Suojelualueet — Pirkanmaa"
theme = "retkikohteet"

[params]
  description = "Pirkanmaan suojelualueet yhdessä paikassa"
  region = "Pirkanmaa"
  mml_api_key = "4ecffb02-3f05-4625-9f21-0db41cc01c97"

enableGitInfo = true

[markup.goldmark.renderer]
  unsafe = true

[mediaTypes."text/css"]
  suffixes = ["css"]
[mediaTypes."text/javascript"]
  suffixes = ["js", "mjs"]

[server]
  [[server.headers]]
    for = "**.css"
    [server.headers.values]
      Content-Type = "text/css; charset=utf-8"
  [[server.headers]]
    for = "**.js"
    [server.headers.values]
      Content-Type = "text/javascript; charset=utf-8"
